name: Sync to Google Cloud Storage

on:
  push:
    branches:
      - main  # Adjust to your default branch (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-etl-458908  # Replace with your GCP project ID

      - name: Sync to GCS
        run: |
          gsutil -m rsync -r ./ gs://etl-testing-data/  # Replace with your bucket name
